sudo: required
services:
  - docker


before_install:
    - docker build -t ashishdhawal/docker-multi -f Dockerfile.dev ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ashishdhawal/docker-multi npm run test -- --coverage

after_success:
  - docker build -t ashishdhawal/doc-multi-client ./client
  - docker build -t ashishdhawal/doc-multi-nginx  ./nginx
  - docker build -t ashishdhawal/doc-multi-server ./server
  - docker build -t ashishdhawal/doc-multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" |  docker login -u "$DOCKER_ID" --password-stdin
  # Take those images & push those images to DockerHub


  

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react-wsl 
  env: DockerReactWsl-env
  bucket_name: "elasticbeanstalk-us-east-2-171912905752"
  bucker_path: docker-react-wsl
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

